#!/usr/bin/env bash
chmod a+w data.sqlite

if [ "$1" != "" ]; then
  FILES=("$1")
else  
  FILES=game/cgi/*.nim
fi

for full_fn in $FILES
do
  just_fn=$(basename -- "${full_fn::-4}")
  nim r --path:"." -d:"debug" --out:/usr/lib/cgi-bin/$just_fn.cgi /var/www/html/$full_fn
done


